client:
  id: 1

spring:
  datasource:
    url: jdbc:postgresql://${TEST_TASK_DB_HOST:localhost}:${TEST_TASK_DB_PORT:5432}/test-task-db
    username: ${TEST_TASK_DB_USER:postgres}
    password: ${TEST_TASK_DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
